version: "2"
services:
  varnish:
    build: varnish
    ports:
    - "80:6081"
    - "6085:6085"
    environment:
      BACKENDS: "wordpress"
      BACKENDS_PORT: "80"
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_USER: "admin"
      DASHBOARD_PASSWORD: "admin"
