version: '2'
services:
  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - '80'
      - '443'
    volumes:
      - appcode-native-osx-sync:/bitnami/wordpress:nocopy
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    environment:
      - MARIADB_HOST=mariadb-master
      - MARIADB_PORT=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  # wordpress:
  #   image: 'bitnami/wordpress:latest'
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - appcode-native-osx-sync:/bitnami/wordpress:nocopy
  #     - 'apache_data:/bitnami/apache'
  #     - 'php_data:/bitnami/php'
  #   depends_on:
  #     - mariadb
  #   environment:
  #     - MARIADB_HOST=mariadb
  #     - MARIADB_PORT=3306
  #     - WORDPRESS_DATABASE_USER=bn_wordpress
  #     - WORDPRESS_DATABASE_NAME=bitnami_wordpress
  #     - RDS_DB_NAME=bitnami_wordpress
  #     - RDS_USERNAME=bn_wordpress
  #     - RDS_PASSWORD=
  #     - RDS_HOSTNAME=mariadb
  #     - ALLOW_EMPTY_PASSWORD=yes
volumes:
  apache_data:
    driver: local
  php_data:
    driver: local
  appcode-native-osx-sync:
    external: true
